### ISSUE TITLE
Can not register github token

### ISSUE THREAD

**Issue by Dobrokhotov1989** [r-lib/gitcreds#31]
When I'm trying to register github tocken, I get the following error. How should I deal with it?

```
gitcreds::gitcreds_set()
#>Error in throw(new_error("gitcreds_nogit_error")) : 
#>  Could not find system git
```

**Comment by gaborcsardi** [comment]
You need to install git to use gitcreds. Do you have git installed? Is it on the `PATH`?

**Comment by Dobrokhotov1989** [comment]
Thank you for the prompt reply. Git was not on the `PATH`. I've added it and now it works.
