### ISSUE TITLE
gitcreds_set / gitcreds_get does not persist between sessions

### ISSUE THREAD

**Issue by jzadra** [r-lib/gitcreds#45]
Every time I start a new R session and want to push/pull to github, I have to use `gitcreds_set()`.  It will work, but then it doesn't work the next time I start an R session.

─ Session info ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.1.3 (2022-03-10)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  C.UTF-8
 ctype    C.UTF-8
 tz       America/Los_Angeles
 date     2022-04-01
 rstudio  2021.09.2+382 Ghost Orchid (desktop)
 pandoc   2.5 @ /usr/bin/pandoc

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.1.2)
 backports     1.4.1      2021-12-13 [1] CRAN (R 4.1.2)
 base64enc     0.1-3      2015-07-28 [1] CRAN (R 4.1.2)
 bitops        1.0-7      2021-04-24 [1] CRAN (R 4.1.2)
 brio          1.1.3      2021-11-30 [1] CRAN (R 4.1.2)
 broom         0.7.12     2022-01-28 [1] CRAN (R 4.1.2)
 cachem        1.0.6      2021-08-19 [1] CRAN (R 4.1.2)
 callr         3.7.0      2021-04-20 [1] CRAN (R 4.0.3)
 cellranger    1.1.0      2016-07-27 [1] CRAN (R 4.1.2)
 cli           3.2.0      2022-02-14 [1] CRAN (R 4.1.2)
 colorspace    2.0-3      2022-02-21 [1] CRAN (R 4.1.2)
 crayon        1.5.0      2022-02-14 [1] CRAN (R 4.1.2)
 curl          4.3.2      2021-06-23 [1] CRAN (R 4.1.2)
 DBI           1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
 dbplyr        2.1.1      2021-04-06 [1] CRAN (R 4.0.3)
 desc          1.4.0      2021-09-28 [1] CRAN (R 4.1.2)
 devtools    * 2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 digest        0.6.29     2021-12-01 [1] CRAN (R 4.1.2)
 dplyr       * 1.0.8      2022-02-08 [1] CRAN (R 4.1.2)
 DT            0.21       2022-02-26 [1] CRAN (R 4.1.2)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.0.3)
 fansi         1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.1.2)
 forcats     * 0.5.1      2021-01-27 [1] CRAN (R 4.1.2)
 fs            1.5.2      2021-12-08 [1] CRAN (R 4.1.2)
 gargle        1.2.0      2021-07-02 [1] CRAN (R 4.0.3)
 generics      0.1.2      2022-01-31 [1] CRAN (R 4.1.2)
 ggplot2     * 3.3.5      2021-06-25 [1] CRAN (R 4.1.2)
 gitcreds      0.1.1      2020-12-04 [1] CRAN (R 4.1.2)
 glue        * 1.6.2      2022-02-24 [1] CRAN (R 4.1.2)
 googleAuthR   2.0.0      2022-01-28 [1] CRAN (R 4.1.2)
 gtable        0.3.0      2019-03-25 [1] CRAN (R 4.1.2)
 haven         2.4.3      2021-08-04 [1] CRAN (R 4.1.2)
 hms           1.1.1      2021-09-26 [1] CRAN (R 4.1.2)
 htmltools     0.5.2      2021-08-25 [1] CRAN (R 4.1.2)
 htmlwidgets   1.5.4      2021-09-08 [1] CRAN (R 4.1.2)
 httr        * 1.4.2      2020-07-20 [1] CRAN (R 4.1.2)
 integral    * 0.0.2.9004 2022-03-23 [1] Github (IntegralEnvision/integral@ad51da5)
 janitor     * 2.1.0      2021-01-05 [1] CRAN (R 4.0.3)
 jsonlite      1.8.0      2022-02-22 [1] CRAN (R 4.1.2)
 lifecycle     1.0.1      2021-09-24 [1] CRAN (R 4.0.3)
 lubridate   * 1.8.0      2021-10-07 [1] CRAN (R 4.0.3)
 magrittr      2.0.2      2022-01-26 [1] CRAN (R 4.1.2)
 memoise       2.0.1      2021-11-26 [1] CRAN (R 4.1.2)
 modelr        0.1.8      2020-05-19 [1] CRAN (R 4.1.2)
 munsell       0.5.0      2018-06-12 [1] CRAN (R 4.1.2)
 pillar        1.7.0      2022-02-01 [1] CRAN (R 4.1.2)
 pkgbuild      1.3.1      2021-12-20 [1] CRAN (R 4.1.2)
 pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.1.2)
 pkgload       1.2.4      2021-11-30 [1] CRAN (R 4.1.2)
 prettyunits   1.1.1      2020-01-24 [1] CRAN (R 4.1.2)
 processx      3.5.2      2021-04-30 [1] CRAN (R 4.0.3)
 ps            1.6.0      2021-02-28 [1] CRAN (R 4.1.2)
 purrr       * 0.3.4      2020-04-17 [1] CRAN (R 4.1.2)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.2)
 Rcpp          1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
 RCurl       * 1.98-1.6   2022-02-08 [1] CRAN (R 4.1.2)
 readr       * 2.1.2      2022-01-30 [1] CRAN (R 4.1.2)
 readxl        1.3.1      2019-03-13 [1] CRAN (R 4.1.2)
 remotes       2.4.2      2021-11-30 [1] CRAN (R 4.1.2)
 reprex        2.0.1      2021-08-05 [1] CRAN (R 4.0.3)
 rjson       * 0.2.21     2022-01-09 [1] CRAN (R 4.1.2)
 rlang         1.0.1      2022-02-03 [1] CRAN (R 4.1.2)
 rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.1.2)
 rrapply     * 1.2.3      2021-02-08 [1] CRAN (R 4.1.2)
 rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.1.2)
 rvest         1.0.2      2021-10-16 [1] CRAN (R 4.0.3)
 scales        1.1.1      2020-05-11 [1] CRAN (R 4.1.2)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.2)
 snakecase     0.11.0     2019-05-25 [1] CRAN (R 4.0.3)
 stringi       1.7.6      2021-11-29 [1] CRAN (R 4.1.2)
 stringr     * 1.4.0      2019-02-10 [1] CRAN (R 4.1.2)
 testthat      3.1.2      2022-01-20 [1] CRAN (R 4.1.2)
 tibble      * 3.1.6      2021-11-07 [1] CRAN (R 4.0.3)
 tidyr       * 1.2.0      2022-02-01 [1] CRAN (R 4.1.2)
 tidyselect    1.1.2      2022-02-21 [1] CRAN (R 4.1.2)
 tidyverse   * 1.3.1      2021-04-15 [1] CRAN (R 4.1.2)
 tzdb          0.2.0      2021-10-27 [1] CRAN (R 4.1.2)
 usethis     * 2.1.5      2021-12-09 [1] CRAN (R 4.1.2)
 utf8          1.2.2      2021-07-24 [1] CRAN (R 4.1.2)
 vctrs         0.3.8      2021-04-29 [1] CRAN (R 4.0.3)
 withr         2.4.3      2021-11-30 [1] CRAN (R 4.1.2)
 xml2          1.3.3      2021-11-30 [1] CRAN (R 4.1.2)

 [1] /usr/local/lib/R/site-library
 [2] /usr/lib/R/site-library
 [3] /usr/lib/R/library

──────────────────

**Comment by gaborcsardi** [comment]
gitcreds interfaces the credential store of git, which can use various credential helpers. Linux does not have a built-in credential store, but there are various options, e.g. GCM: https://github.com/GitCredentialManager/git-credential-manager
