### ISSUE TITLE
Set token non-interactively

### ISSUE THREAD

**Issue by royfrancis** [r-lib/gitcreds#62]
I am installing packages from GitHub in a docker container and running into rate limiting. How does one set token non-interactively from an environment variable?

I am thinking of something like this..

```
gitcreds_set(url = "https://github.com", token = Sys.getenv("TOKEN"))
```

Perhaps, I am missing something.

**Comment by gaborcsardi** [comment]
Do want to use a credential helper on GitHub? Or what are you "setting" the token for?

**Comment by gaborcsardi** [comment]
remotes will pick up the `GITHUB_PAT` environment variable, no need to use a credential helper.

Or even better, use https://github.com/r-lib/actions/tree/v2-branch/setup-r-dependencies, look at the suggested workflows here: https://github.com/r-lib/actions/tree/v2-branch/examples
